language: java
jdk:
  - oraclejdk8

env:
  global:
    - CC_ENV=travis-ci
  matrix:
    - CC_BOOT=default
script:
  - ant boot -Daccept.license=true
  - ~/sag/cc/CommandCentral/client/bin/sagccant up
  - ~/sag/cc/CommandCentral/client/bin/sagccant mirrors mirrors2
#  - ~/sag/cc/CommandCentral/client/bin/sagccant mirrors mirrors2 -Drelease=9.12
